services:
  cognecto-web:
    build: .
    container_name: cognecto-website
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: always
    depends_on:
      - cognecto-api

  cognecto-api:
    build: ./api
    container_name: cognecto-api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL:-info@cognecto.com}
    env_file:
      - ./api/.env
    restart: always
